[package]
name = "client"
version = "0.1.0"
authors = ["Navomi Byju (nbyju2), Daniel Andrasz (da22), Akhil Bharanidhar (akhilnb2)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
